import type { PopulatedSchemaGenerationConfig } from "./schema-generation-config";
import type { EnumType, TableToGenerate } from "./table-parser";

const header = `
// This file is generated by the generate-schema.ts script.
// Do not edit this file manually.

import { z } from "zod";
`.trim();

const schemaHeader = (config: PopulatedSchemaGenerationConfig): string =>
  `
export const ${config.schemaExportName} = {
`.trim();

const footer = (config: PopulatedSchemaGenerationConfig): string =>
  `
};

type Schemas = typeof ${config.schemaExportName};
type RowTypes = {
  [K in keyof Schemas]: Schemas[K]["types"] & {
    notNull: Schemas[K]["notNullTypes"];
  };
};

export const rowTypes: RowTypes = Object.fromEntries(
  Object.entries(${config.schemaExportName}).map(([key, value]) => [
    key,
    { ...value.types, notNull: value.notNullTypes },
  ]),
) as unknown as RowTypes;
`.trim();

const generateTableSchema = (
  table: TableToGenerate,
  config: PopulatedSchemaGenerationConfig,
): string => {
  const transformedTableName = config.tableNameTransform(table.name);
  return `  ${transformedTableName}: {
    tableName: "${table.name}",
    types: {
      ${table.columns.map((column) => `${config.columnNameTransform(column.name)}:  ${column.isPrimaryKey ? `${transformedTableName}${config.primaryKeySuffix}Schema` : column.zodType},`).join("\n      ")}
    },
    notNullTypes: {
      ${table.columns.map((column) => `${config.columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config.primaryKeySuffix}Schema` : column.zodTypeWithoutNullable},`).join("\n      ")}
    },
    validator: z.object({
      ${table.columns.map((column) => `${config.columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config.primaryKeySuffix}Schema` : column.zodType},`).join("\n      ")}
    })${table.isView ? "" : ".strict()"},
    notNullValidator: z.object({
      ${table.columns.map((column) => `${config.columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config.primaryKeySuffix}Schema` : column.zodTypeWithoutNullable},`).join("\n      ")}
    })${table.isView ? "" : ".strict()"},
  },
  `.trimEnd();
};

const generateRowTypeExports = (
  tables: TableToGenerate[],
  config: PopulatedSchemaGenerationConfig,
): string => {
  return `
  ${tables
    .map((table) => {
      const transformedTableName = config.tableNameTransform(table.name);
      return `export const ${transformedTableName} = rowTypes.${transformedTableName};`;
    })
    .join("\n")}
  `.trim();
};

const generateTableId = (
  table: TableToGenerate,
  config: PopulatedSchemaGenerationConfig,
): string => {
  const idColumn = table.columns.find((column) => column.isPrimaryKey);
  if (!idColumn) {
    return "";
  }

  const transformedTableName = config.tableNameTransform(table.name);
  return `
export const ${transformedTableName}${config.primaryKeySuffix}Schema = ${idColumn.zodTypeWithoutNullable}.brand<"${transformedTableName}${config.primaryKeySuffix}">();
export type ${transformedTableName}${config.primaryKeySuffix} = z.infer<typeof ${transformedTableName}${config.primaryKeySuffix}Schema>;
`.trim();
};

const generateTableTypeExport = (
  table: TableToGenerate,
  config: PopulatedSchemaGenerationConfig,
): string => {
  const transformedTableName = config.tableNameTransform(table.name);
  return `
export type ${transformedTableName}${config.tableTypeSuffix} = z.infer<typeof ${config.schemaExportName}.${transformedTableName}.validator>;
export type ${transformedTableName}${config.tableTypeSuffix}NotNull = z.infer<typeof ${config.schemaExportName}.${transformedTableName}.notNullValidator>;
  `.trim();
};

const generateEnumSchema = (enumType: EnumType): string => {
  const labels = enumType.labels.map((l) => `"${l}"`).join(", ");
  return `
  export const ${enumType.name}Schema = z.enum([${labels}]);
  export type ${enumType.name} = z.infer<typeof ${enumType.name}Schema>;
  `;
};

export const generateSchemaTypescript = (
  tables: TableToGenerate[],
  enums: EnumType[],
  config: PopulatedSchemaGenerationConfig,
): string => {
  return `
${header}
${enums.map((e) => generateEnumSchema(e)).join("\n")}
${tables.map((table) => generateTableId(table, config)).join("\n")}

${schemaHeader(config)}
${tables.map((table) => generateTableSchema(table, config)).join("\n")}
${footer(config)}

${tables.map((table) => generateTableTypeExport(table, config)).join("\n")}

${generateRowTypeExports(tables, config)}

  `.trim();
};
